### ISSUE TITLE
Sammler: Wichtige Plugins berücksichtigen und Gestaltungselemente (oder Klassen) hierfür bereitstellen

### ISSUE THREAD

**Issue by lukasniebler** [FAU-Brand/Lastenheft#20]
Es gibt verschiedene selbstentwickelte Plugins, die im neuen Theme mitgestaltet werden sollten.
## Die wichtigsten Plugins
 mit HMLT output, welche im alten Theme gestaltet wurden:
- [ ] FAU-Brand/Designelemente#25 
- [ ] FAU-Brand/Designelemente#26 
- [ ] FAU-Brand/Designelemente#27 
- [ ] FAU-Brand/Designelemente#28 
- [ ] FAU-Brand/Designelemente#17 

Ansonsten sollten im Abgleich mit [src/sass/plugins](https://github.com/RRZE-Webteam/FAU-Einrichtungen/tree/master/src/sass/plugins) aufgeführte RRZE-eigene Plugins geprüft werden, ob die Ausgabe der gelisteten Plugins auf Testseiten wie erwartet mit dem neuen Theme dargestellt und genutzt werden können.

Wichtig: Es geht bei den Plugins nicht um Funktionalität, sondern um die reine Gestaltung.

Alle Gestaltungselemente, die die Plugins für die Ausgabe von Inhalten brauchen, muss das Theme bereitstellen.
Wenn eine Ausgabe von Inhalten aus Plugins schlecht aussieht mit dem neuen Theme, dann wurde bei dem Theme entweder ein Fehler gemacht oder was vergessen zu definieren.
Die Ausgabe von Plugins eigenen sich daher zur Abnahme und zum Test des Themes.
